trigger:
  - master

variables:
  version: '3.0'

# stages
stages:
  # build stage
  - stage: build
    displayName: 'Jupiter Build'
    # build stage jobs
    jobs:
      # Linux job
      - template: src/pipeline/build.yml
        parameters:
          name: Linux
          platform: linux
          version: $(version)
          pool:
            vmImage: 'ubuntu-16.04'
      # Mac OS job
      - template: src/pipeline/build.yml
        parameters:
          name: MacOS
          platform: mac
          version: $(version)
          pool:
            vmImage: 'macOS-10.13'
      # Windows job
      - template: src/pipeline/build.yml
        parameters:
          name: Windows
          platform: win
          version: $(version)
          pool:
            vmImage: 'windows-2019'
