parameters:
  name: ''
  pool: ''
  platform: ''
  version: ''

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        tasks: 'codecov'
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'JaCoCo'
        summaryFileLocation: './build/reports/jacoco/test/jacocoTestReport.xml'
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        tasks: 'jlinkZip'
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: './build/distributions/Jupiter-${{ parameters.version }}-${{ parameters.platform }}.zip'
