# Project Information
site_name: Jupiter
site_description: 'RISC-V Assembler and Runtime Simulator'
site_author: 'Andrés Castellanos &amp; Inés Ramirez'
site_url: https://www.riscvsim.com/

# Repository
edit_uri: edit/master/docs/en/docs
repo_name: andrescv/Jupiter
repo_url: https://github.com/andrescv/Jupiter/

# Copyright
copyright: 'Copyright &copy; 2018-2019, Andrés Castellanos &amp; Inés Ramirez'

# Theme Configuration
theme:
  name: material
  language: en
  custom_dir: ../assets
  favicon: 'images/icon.png'
  logo: 'images/icon.png'
  palette:
    primary: white
    accent: blue grey

# Customization
extra:
  social:
    - type: github
      link: https://github.com/andrescv/Jupiter/

# javascript
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# Google Analytics
google_analytics:
  - 'UA-131956264-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - footnotes

# Navigation
nav:
  - Home: index.md
