site_name: V-Sim Documentation
site_description: 'V-Sim: RISC-V Assembler and Runtime Simulator'
site_author: 'Andrés Castellanos'
copyright: '© Copyright 2018, Andrés Castellanos'

theme:
  name: readthedocs
  custom_dir: theme

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML

site_url: https://github.com/andrescv/V-Sim
repo_url: https://github.com/andrescv/V-Sim

pages:
  - Home: index.md
  - User Guide:
    - Using V-Sim: usage.md
    - Directives: directives.md
    - Environmental Calls: ecalls.md
  - License: license.md
